#!/bin/bash
set -e

INPUT="${1:-$HOME/Downloads/niko.jpg}"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
OUTPUT="$SCRIPT_DIR/niko_image.h"

if [ ! -f "$INPUT" ]; then
    echo "Error: $INPUT not found" >&2
    exit 1
fi

TMP=$(mktemp /tmp/niko_raw.XXXXXX.rgb)
trap "rm -f $TMP" EXIT

echo "Converting $INPUT -> 432x432, replacing white bg with #0a0010..."

magick "$INPUT" \
    -filter point \
    -scale 432x432 \
    -fuzz 20% \
    -fill '#0a0010' \
    -opaque white \
    -type TrueColor \
    -depth 8 \
    "RGB:$TMP"

python3 - "$TMP" "$OUTPUT" 432 432 <<'PYEOF'
import sys

raw_file, out_file = sys.argv[1], sys.argv[2]
w, h = int(sys.argv[3]), int(sys.argv[4])

with open(raw_file, 'rb') as f:
    data = f.read()

expected = w * h * 3
if len(data) != expected:
    print(f"Error: expected {expected} bytes, got {len(data)}", file=sys.stderr)
    sys.exit(1)

with open(out_file, 'w') as f:
    f.write("/* Auto-generated by gen_image.sh -- do not edit */\n")
    f.write("#pragma once\n")
    f.write(f"#define NIKO_W {w}\n")
    f.write(f"#define NIKO_H {h}\n")
    f.write(f"static const unsigned char niko_pixels[{w * h * 3}] = {{\n")
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        f.write('    ' + ', '.join(f'0x{b:02x}' for b in chunk) + ',\n')
    f.write("};\n")

print(f"Generated {out_file} ({w}x{h}, {len(data):,} bytes)")
PYEOF

echo "Done: $OUTPUT"
